[package]
name = "vessel"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy_flycam = "0.14.1"

[dependencies.derive_more]
version = "1.0.0"
features = ["from","into"]

[dependencies.bevy_mod_picking]
version = "0.20.1"
default-features = false
features = [
	"backend_raycast",
	"debug",
	"highlight"
]

[dependencies.bevy]
version = "0.14"
features = ["dynamic_linking"]
